_wandb:
    value:
        cli_version: 0.23.0
        e:
            pf55zqy6aotxjuvmb3asaag1i3dr7bbk:
                args:
                    - --grid_size
                    - "3"
                    - --num_cubes
                    - "4"
                    - --timesteps
                    - "50"
                    - --ddqn_model_path
                    - C:\isaacsim\cobotproject\scripts\Reinforcement Learning\doubleDQN_script\models\ddqn_rrt_viz_grid3_cubes4_20251220_025425_final.pt
                    - --run_name
                    - grid3x3_4cubes_rrt_test
                    - --config_name
                    - grid3x3_4cubes
                    - --log_interval
                    - "1"
                    - --save_interval
                    - "50"
                codePath: train_rrt_mappo.py
                codePathLocal: train_rrt_mappo.py
                cpu_count: 20
                cpu_count_logical: 28
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "1022880641024"
                        used: "748639440896"
                executable: C:\isaacsim\kit\python\kit.exe
                gpu: NVIDIA RTX 3500 Ada Generation Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 5120
                      memoryTotal: "12878610432"
                      name: NVIDIA RTX 3500 Ada Generation Laptop GPU
                      uuid: GPU-f3c2eeb3-17e9-4df8-c80a-1c7aa17f7ea8
                host: CRD-SIMULATION5
                memory:
                    total: "33999233024"
                os: Windows-10-10.0.26200-SP0
                program: C:\isaacsim\cobotproject\scripts\Reinforcement Learning\MAPPO\train\train_rrt_mappo.py
                python: CPython 3.11.13
                root: C:\isaacsim\cobotproject\scripts\Reinforcement Learning\MAPPO\train
                startedAt: "2026-01-14T22:20:48.787995Z"
                writerId: pf55zqy6aotxjuvmb3asaag1i3dr7bbk
        m:
            - "1": global_step
              "6":
                - 3
              "7": []
            - "2": mappo/*
              "5": 1
              "6":
                - 1
              "7": []
            - "2": training/*
              "5": 1
              "6":
                - 1
              "7": []
            - "2": train/*
              "5": 1
              "6":
                - 1
              "7": []
            - "2": episode/*
              "5": 1
              "6":
                - 1
              "7": []
            - "2": reshuffle/*
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 105
            "2":
                - 1
                - 105
            "3":
                - 2
                - 7
                - 13
                - 15
                - 16
            "4": 3.11.13
            "5": 0.23.0
            "8":
                - 2
                - 3
            "12": 0.23.0
            "13": windows-amd64
batch_size:
    value: 64
buffer_size:
    value: 256
clip_param:
    value: 0.2
config_name:
    value: grid3x3_4cubes
ddqn_model_path:
    value: C:\isaacsim\cobotproject\scripts\Reinforcement Learning\doubleDQN_script\models\ddqn_rrt_viz_grid3_cubes4_20251220_025425_final.pt
device:
    value: cuda
entropy_coef:
    value: 0.01
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
grid_size:
    value: 3
log_interval:
    value: 1
lr:
    value: 0.0003
max_grad_norm:
    value: 0.5
max_reshuffles:
    value: 5
max_steps:
    value: 50
num_cubes:
    value: 4
num_mini_batch:
    value: 4
ppo_epochs:
    value: 10
reshuffle_reward_scale:
    value: 1
resume:
    value: null
run_name:
    value: grid3x3_4cubes_rrt_test
save_interval:
    value: 50
seed:
    value: 42
timesteps:
    value: 50
value_loss_coef:
    value: 1
wandb_project:
    value: ddqn-mappo-object-selection-reshuffling
